### ISSUE TITLE
.getVue() seems not working

### ISSUE THREAD

**Issue by mruanGitHub** [DevExpress/testcafe-vue-selectors#55]
.getVue() method seems NOT working!

I can not find .getVue() in MS code. It shows "no definition for getVue()". Another problem is the TS7016: could not find the declaration file for testcafe-vue-selectors.

**Comment by mruanGitHub** [comment]
TS7016 :
![image](https://user-images.githubusercontent.com/22932196/119471665-caf13600-bd49-11eb-9eaf-6c9e423ec500.png)

The two suggested solutions do not work!
Does this cause the following problem?

![image](https://user-images.githubusercontent.com/22932196/119472052-2b807300-bd4a-11eb-9954-43ba0043e5e7.png)

**Comment by aleks-pro** [comment]
Hello @mruanGitHub,

The `testcafe-vue-selectors` plugin does not contain type definitions. You can use the [`@ts-ignore`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html#suppress-errors-in-ts-files-using--ts-ignore-comments) comment to avoid errors related to it.
Since `testcafe-vue-selectors` is an open source project, you can create a pull request to add type definitions to it.
